# == Schema Information
#
# Table name: hypertexts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HypertextsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Hypertext. As you add validations to Hypertext, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HypertextsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all hypertexts as @hypertexts" do
      hypertext = Hypertext.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:hypertexts)).to eq([hypertext])
    end
  end

  describe "GET #show" do
    it "assigns the requested hypertext as @hypertext" do
      hypertext = Hypertext.create! valid_attributes
      get :show, {:id => hypertext.to_param}, valid_session
      expect(assigns(:hypertext)).to eq(hypertext)
    end
  end

  describe "GET #new" do
    it "assigns a new hypertext as @hypertext" do
      get :new, {}, valid_session
      expect(assigns(:hypertext)).to be_a_new(Hypertext)
    end
  end

  describe "GET #edit" do
    it "assigns the requested hypertext as @hypertext" do
      hypertext = Hypertext.create! valid_attributes
      get :edit, {:id => hypertext.to_param}, valid_session
      expect(assigns(:hypertext)).to eq(hypertext)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Hypertext" do
        expect {
          post :create, {:hypertext => valid_attributes}, valid_session
        }.to change(Hypertext, :count).by(1)
      end

      it "assigns a newly created hypertext as @hypertext" do
        post :create, {:hypertext => valid_attributes}, valid_session
        expect(assigns(:hypertext)).to be_a(Hypertext)
        expect(assigns(:hypertext)).to be_persisted
      end

      it "redirects to the created hypertext" do
        post :create, {:hypertext => valid_attributes}, valid_session
        expect(response).to redirect_to(Hypertext.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved hypertext as @hypertext" do
        post :create, {:hypertext => invalid_attributes}, valid_session
        expect(assigns(:hypertext)).to be_a_new(Hypertext)
      end

      it "re-renders the 'new' template" do
        post :create, {:hypertext => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hypertext" do
        hypertext = Hypertext.create! valid_attributes
        put :update, {:id => hypertext.to_param, :hypertext => new_attributes}, valid_session
        hypertext.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested hypertext as @hypertext" do
        hypertext = Hypertext.create! valid_attributes
        put :update, {:id => hypertext.to_param, :hypertext => valid_attributes}, valid_session
        expect(assigns(:hypertext)).to eq(hypertext)
      end

      it "redirects to the hypertext" do
        hypertext = Hypertext.create! valid_attributes
        put :update, {:id => hypertext.to_param, :hypertext => valid_attributes}, valid_session
        expect(response).to redirect_to(hypertext)
      end
    end

    context "with invalid params" do
      it "assigns the hypertext as @hypertext" do
        hypertext = Hypertext.create! valid_attributes
        put :update, {:id => hypertext.to_param, :hypertext => invalid_attributes}, valid_session
        expect(assigns(:hypertext)).to eq(hypertext)
      end

      it "re-renders the 'edit' template" do
        hypertext = Hypertext.create! valid_attributes
        put :update, {:id => hypertext.to_param, :hypertext => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested hypertext" do
      hypertext = Hypertext.create! valid_attributes
      expect {
        delete :destroy, {:id => hypertext.to_param}, valid_session
      }.to change(Hypertext, :count).by(-1)
    end

    it "redirects to the hypertexts list" do
      hypertext = Hypertext.create! valid_attributes
      delete :destroy, {:id => hypertext.to_param}, valid_session
      expect(response).to redirect_to(hypertexts_url)
    end
  end

end
